# metadata_backfill_daily.ps1 — D052d + D052h-fixup3 + D052h-fixup4
# Daily 18:10 cron: scan daily_data2_full latest date for tickers missing
# from industry_type, pass as --batch to metadata_backfill.py.
# Per ChatGPT F7: must run AFTER 17:35+17:55 OHLCV landing, BEFORE 22:25
# daily-report, so the new tickers get a row in industry_type and their
# HTML files can be generated by the daily run.
#
# D052h-fixup3:
#   - target_date and missing-tickers list come from a SINGLE Python
#     invocation (one DB connection, one snapshot). Previously the .ps1
#     used two separate `python -c` calls; between the two, OHLCV could
#     land and shift MAX(Date) -> query 1 (missing tickers) would have
#     scanned a different date than the marker stamped.
#   - missing-tickers SQL uses the explicit target_date parameter, not
#     a sub-select on MAX(Date) (which would be a 2nd snapshot).
#   - marker is written via same-directory temp file + Move-Item
#     (atomic rename on NTFS) so market_screen_runner never observes
#     a half-written marker.
#
# D052h-fixup4:
#   - Marker is written as UTF-8 *without* BOM. The previous
#     `Set-Content -Encoding UTF8` (default on Windows PowerShell 5.1)
#     emits a BOM (EF BB BF), which the Python consumer (D052h-fixup3
#     and earlier) could not strip — has_metadata_marker would return
#     False because the first key parsed as "\ufefftarget_date".
#     Windows PowerShell 5.1 has no `utf8NoBOM` encoding literal, so
#     we use [System.IO.File]::WriteAllText with a UTF8Encoding $False
#     instance (encoderShouldEmitUTF8Identifier = $False). The Python
#     consumer is also updated (D052h-fixup4: utf-8-sig) to accept
#     either form, so existing BOM markers still validate while new
#     markers are produced BOM-less.
#
# Path strategy: this .ps1 lives in BOTH C:\Users\icemo\Projects\tw-invest-suite\scripts\
# (git repo) and C:\Users\icemo\.claude\skills\tw-invest-suite\scripts\ (runtime). The
# actual python script metadata_backfill.py is only in the git repo. We use
# absolute path to the git repo so cron works regardless of where the .ps1
# is called from.
$ErrorActionPreference = "Stop"
$env:PYTHONIOENCODING = "utf-8"
$RepoScript = "C:\Users\icemo\Projects\tw-invest-suite\scripts\metadata_backfill.py"
$LogDir = "C:\Users\icemo\.claude\skills\tw-invest-suite\scripts\_debug"
$MarkerDir = "C:\Users\icemo\Projects\tw-invest-suite\scripts\_debug"
$LogFile = Join-Path $LogDir ("metadata_backfill_" + (Get-Date -Format "yyyyMMdd_HHmmss") + ".log")
$Python = "python"

New-Item -ItemType Directory -Force -Path $LogDir | Out-Null
New-Item -ItemType Directory -Force -Path $MarkerDir | Out-Null

# 1. ONE Python call computes both target_date AND missing tickers
#    from the SAME connection/snapshot. Output is two lines:
#      line 1: <target_date ISO>
#      line 2: <comma-joined missing tickers>  (empty string if none)
$Snapshot = & $Python -c "
import pymysql
c = pymysql.connect(host='localhost', user='root', password='1234', database='tw_elec', connect_timeout=10, charset='utf8mb4')
cur = c.cursor()
cur.execute('SELECT MAX(Date) FROM daily_data2_full')
r = cur.fetchone()
if not r or not r[0]:
    print('')
    print('')
    raise SystemExit(0)
target = r[0]
cur.execute('SELECT d.ticker FROM daily_data2_full d LEFT JOIN industry_type i ON d.ticker = i.ticker WHERE d.Date = %s AND i.ticker IS NULL GROUP BY d.ticker', (target,))
missing = sorted(row[0] for row in cur.fetchall())
print(target.isoformat())
print(','.join(missing))
"
if ($LASTEXITCODE -ne 0) {
    Write-Error "[metadata-backfill-daily] FATAL: snapshot query exit $LASTEXITCODE. aborting."
    exit 1
}
$TargetDate = ($Snapshot -split "`n")[0].Trim()
$Missing = ($Snapshot -split "`n")[1].Trim()

Write-Output "[metadata-backfill-daily] target_date = $TargetDate  missing tickers: $Missing"
if ([string]::IsNullOrWhiteSpace($TargetDate)) {
    Write-Error "[metadata-backfill-daily] FATAL: empty target_date (DB has no data). aborting."
    exit 1
}

# 2. ALWAYS remove any prior marker for this target_date so a stale
#    success marker from a previous day cannot satisfy today's market-screen.
$MarkerFile = Join-Path $MarkerDir ("metadata_target_${TargetDate}_OK.marker")
if (Test-Path $MarkerFile) {
    Remove-Item $MarkerFile -Force
    Write-Output "[metadata-backfill-daily] removed prior marker: $MarkerFile"
}

if ([string]::IsNullOrWhiteSpace($Missing)) {
    Write-Output "[metadata-backfill-daily] no missing tickers, nothing to do"
    # Still write the marker — metadata ran successfully (and found nothing).
} else {
    # 3. Call metadata_backfill.py with the missing tickers as --batch
    Write-Output "=== metadata_backfill_daily $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss') ==="
    Write-Output "  Script: $RepoScript"
    Write-Output "  Args:   --batch=$Missing"
    try {
        & $Python $RepoScript "--batch=$Missing" 2>&1 | Tee-Object -FilePath $LogFile
        if ($LASTEXITCODE -ne 0) { throw "exit $LASTEXITCODE" }
        Write-Output "=== metadata_backfill_daily OK ==="
    } catch {
        Write-Error "metadata_backfill_daily FAILED: $_"
        exit 1
    }
}

# 4. Atomic marker write: temp file in same directory, then Move-Item.
#    Move-Item within the same NTFS volume is atomic, so market_screen_runner
#    either sees the previous marker or the new one, never a half-written one.
#    D052h-fixup4: write UTF-8 without BOM. Use [System.IO.File]::WriteAllText
#    with a UTF8Encoding($false) instance — this is the only reliable way
#    to suppress the BOM on Windows PowerShell 5.1 (no `utf8NoBOM`
#    encoding literal exists in 5.1). The Python consumer (market_screen_runner
#    D052h-fixup4) reads with utf-8-sig so it still accepts legacy BOM
#    markers written by older runs.
$MissingCount = if ([string]::IsNullOrWhiteSpace($Missing)) { 0 } else { ($Missing -split ',').Count }
$MarkerContent = @"
target_date=$TargetDate
finished_at=$(Get-Date -Format 'o')
missing_count=$MissingCount
status=ok
"@
$TempMarker = Join-Path $MarkerDir ("metadata_target_${TargetDate}_OK.marker.tmp." + (Get-Date -Format 'HHmmssffff'))
$Utf8NoBom = New-Object System.Text.UTF8Encoding($False)
[System.IO.File]::WriteAllText($TempMarker, $MarkerContent, $Utf8NoBom)
Move-Item -Path $TempMarker -Destination $MarkerFile -Force
Write-Output "[metadata-backfill-daily] wrote success marker (atomic, UTF-8 no BOM): $MarkerFile"
exit 0
