# metadata_backfill_daily.ps1 — D052d
# Daily 18:05 cron: scan daily_data2_full latest date for tickers missing
# from industry_type, pass as --batch to metadata_backfill.py.
# Per ChatGPT F7: must run AFTER 17:35+17:55 OHLCV landing, BEFORE 22:25
# daily-report, so the new tickers get a row in industry_type and their
# HTML files can be generated by the daily run.
#
# Path strategy: this .ps1 lives in BOTH C:\Users\icemo\Projects\tw-invest-suite\scripts\
# (git repo) and C:\Users\icemo\.claude\skills\tw-invest-suite\scripts\ (runtime). The
# actual python script metadata_backfill.py is only in the git repo. We use
# absolute path to the git repo so cron works regardless of where the .ps1
# is called from.
$ErrorActionPreference = "Stop"
$env:PYTHONIOENCODING = "utf-8"
$RepoScript = "C:\Users\icemo\Projects\tw-invest-suite\scripts\metadata_backfill.py"
$LogDir = "C:\Users\icemo\.claude\skills\tw-invest-suite\scripts\_debug"
$LogFile = Join-Path $LogDir ("metadata_backfill_" + (Get-Date -Format "yyyyMMdd_HHmmss") + ".log")
$Python = "python"

New-Item -ItemType Directory -Force -Path $LogDir | Out-Null

# 1. Find tickers in daily_data2_full latest date that are missing from
#    industry_type.
$Missing = & $Python -c "
import pymysql
c = pymysql.connect(host='localhost', user='root', password='1234', database='tw_elec', connect_timeout=10, charset='utf8mb4')
cur = c.cursor()
cur.execute('''SELECT d.ticker
               FROM daily_data2_full d
               LEFT JOIN industry_type i ON d.ticker = i.ticker
               WHERE d.Date = (SELECT MAX(Date) FROM daily_data2_full)
                 AND i.ticker IS NULL
               GROUP BY d.ticker''')
print(','.join(r[0] for r in cur.fetchall()))
"

Write-Output "[metadata-backfill-daily] missing tickers: $Missing"
if ([string]::IsNullOrWhiteSpace($Missing)) {
    Write-Output "[metadata-backfill-daily] no missing tickers, nothing to do"
    exit 0
}

# 2. Call metadata_backfill.py with the missing tickers as --batch
Write-Output "=== metadata_backfill_daily $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss') ==="
Write-Output "  Script: $RepoScript"
Write-Output "  Args:   --batch=$Missing"
try {
    & $Python $RepoScript "--batch=$Missing" 2>&1 | Tee-Object -FilePath $LogFile
    if ($LASTEXITCODE -ne 0) { throw "exit $LASTEXITCODE" }
    Write-Output "=== metadata_backfill_daily OK ==="
} catch {
    Write-Error "metadata_backfill_daily FAILED: $_"
    exit 1
}
