"""Audit: which of the 5 features are present"""
import json

j = json.load(open('E:/Users/icemo/Projects/tw-invest-suite/public/data/chips-advanced.json'))
feats = j['features']
print(f'=== 5 features audit ===')
print(f'total tickers in chips-advanced.json: {len(feats)}')
sample = feats[0]
print()
print(f'[1] 法人分項深度 (今日/5日/20日)  [{sample["ticker"]}]:')
print(f'   5d 3 法人合計: {sample["cum_5d_shares"]:.0f} 股')
print(f'   20d 外資:     {sample["cum_20d_f_shares"]:.0f} 股')
print(f'   20d 投信:     {sample["cum_20d_t_shares"]:.0f} 股')
print(f'   20d 自營:     {sample.get("cum_20d_d_shares", 0):.0f} 股')
print()
print(f'[2] 法人 20 日均價 (VWAP):')
print(f'   vwap_buy_20d: {sample["vwap_buy_20d"]}')
print(f'   vs_vwap_pct:   {sample["vs_vwap_pct"]}%')
print()
print(f'[3] 外資停留天數:')
print(f'   f_stay_days:  {sample["f_stay_days"]}')
print(f'   f_stay_dir:   {sample["f_stay_dir"]}  (1=買, -1=賣)')
print()
print(f'[4] 力道標 (今日/5d 均):')
print(f'   force_ratio:  {sample["force_ratio"]}')
print()
chips = json.load(open('E:/Users/icemo/Projects/tw-invest-suite/public/data/chips.json'))
print(f'[5] 外資連買/連賣 3+ 天:')
print(f'   f_consec_buy: {len(chips["tabs"]["f_consec_buy"])} 檔')
print(f'   f_consec_sell: {len(chips["tabs"]["f_consec_sell"])} 檔')
print()
print('=== Summary: what is where ===')
print('chips.html        : 今日+5日 chip, 連買/連賣 3+ 天 tabs, 同買/同賣')
print('chips-advanced.html: 20d 分項, VWAP 折溢價, 雷達, 力道, f_stay_days')
print('monitor.html      : 5d chip + 自選 + alerts (土洋同買/對作)')
print()
print('缺口:')
print('  - chips.html 卡片沒顯示 f_stay_days (停留天數)')
print('  - chips.html 卡片沒顯示 force_ratio (力道標)')
print('  - 法人 20 日均價只有 % 差，沒有實際價位線圖')
